### PR TITLE
(#43) allow user get cookie by name

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Comment by dannypsnl** [comment]
Don't close #43 in this PR

**Comment by shana0440** [comment]
I think `(h *handler) context` is too large.
Make it hard to read.
Do you think we should open another issue to solve this problem?

**Comment by dannypsnl** [comment]
@shana0440 I don't think it needs a new issue since the reason of complexity of context is introduced by this issue.

**Comment by shana0440** [comment]
ok, the context is a little be complex, but it still readable, so I not sure it should be fixed in this PR or not.

**Comment by dannypsnl** [comment]
I just make conditions more clear. I found a reason might good to open new issue is making a cache for parameters object.

**Pull request merged**
