### PR TITLE
(#41) add: prototype of file MIME type

### PR DESCRIPTION
**Pull request by dannypsnl**
Just a prototype, need to have a discussion

### CODE REVIEW

**Comment by dannypsnl** [comment]
@shana0440 How about `ByFileSuffix(map[string]string`

```go
ByFileSuffix(map[string]string{
    "html": "text/html",
    "css": "text/css",
})
```

**Comment by shana0440** [comment]
I prefer use `response.File(filepath)` instead `file.Response(fs.FileName)` to handle static file.
I hope only one which can decide response body is response package.

**Comment by dannypsnl** [comment]
Yes, I think you're right, package `file` is not good idea

**Comment by dannypsnl** [comment]
TODO: improve coverage

**Comment by dannypsnl** [comment]
I would like to redesign this part, and I would prefer using `interface` for this part rather implement something for this.

**Pull request closed without merging**
