### PR TITLE
(#88) fix: 403 handler bug, forget set offset caused panic

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Comment by shana0440** [comment]
@dannypsnl  which case will cause panic?

**Comment by shana0440** [comment]
I find it, nevermind

**Comment by dannypsnl** [comment]
Should be every time, I don't why it pass before.

**Comment by dannypsnl** [comment]
What? How can it be 😂😂😂.

**Comment by dannypsnl** [comment]
But seems better to add `go test` command in CI script?

**Comment by shana0440** [comment]
looks like server_test is failed, but testcase of response pass, so command still returns 0, cause travis ci pass everytime.

**Comment by dannypsnl** [comment]
image
Yes, you're right, so I think I should add go test command to make them be different

**Comment by dannypsnl** [comment]
Nope, just add, not instead of

**Pull request merged**
