### PR TITLE
test: fix & add benchmark into CI build

### PR DESCRIPTION
**Pull request by dannypsnl**
I just found it broke so quickly fix it.

### CODE REVIEW

**Comment by shana0440** [comment]
If we add benchmark into CI script, do you think we should auto-generate benchmark report?

**Comment by dannypsnl** [comment]
That would be great, but where can we put it

**Comment by shana0440** [comment]
I think we can follow this link.
https://beachape.com/blog/2016/11/02/rust-performance-testing-on-travis-ci/#getting-benchmark-comparisons-in-pull-requests

and this is the package used to compare performance.
https://godoc.org/golang.org/x/tools/cmd/benchcmp

**Comment by dannypsnl** [comment]
default
No result XDDD

**Pull request merged**
