### PR TITLE
refactor: this is better than use Expires

### PR DESCRIPTION
**Pull request by dannypsnl**
MaxAge < 0 is delete now, it's better than setting time 0

### CODE REVIEW

**Comment by shana0440** [comment]
maybe change `cookie.Expires` to  `cookie.MaxAge()` together ?

**Comment by shana0440** [comment]
looks like the difference is IE support or not.
So `Forget` still need to use expires if we want to support IE

**Comment by shana0440** [comment]
I think we can provide two way, but `Forget` should use expries.

**Comment by dannypsnl** [comment]
That means better to abort this PR.

**Pull request closed without merging**
